// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NextensTaxTool.Context;

namespace NextensTaxTool.Migrations
{
    [DbContext(typeof(NextensDbContext))]
    partial class NextensDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NextensTaxTool.Entities.ClientFinancialData", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<long?>("BankBalanceNational")
                        .HasColumnType("bigint");

                    b.Property<long?>("BankbalanceInternational")
                        .HasColumnType("bigint");

                    b.Property<string>("ClientId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("Income")
                        .HasColumnType("bigint");

                    b.Property<long?>("RealEstatePropertyValue")
                        .HasColumnType("bigint");

                    b.Property<long?>("StockInvestments")
                        .HasColumnType("bigint");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ClientFinancialData");
                });
#pragma warning restore 612, 618
        }
    }
}
